In [1]:
from myscripts import exchanges_stats, unlocks_report
from tools import data_preparation as dp
from postgres import executions

import pandas as pd
import numpy as np
import webbrowser
import requests
import datetime
import os
import sys

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

In [2]:
import os
print(os.getcwd())

C:\Users\kocin\Desktop\crypto\supplier\notebooks\reports

<font size="7">BINANCE_FUTURES_MARKETS</font>

In [3]:
save_watchlist=True
save_in_db=True
main_quote_currency='USDT'
secondary_quote_currency='BUSD'
turnover_threshold = '30 000 000'

In [4]:
binancefut = exchanges_stats.BinanceFuturesStats(save_watchlist, save_in_db, main_quote_currency, secondary_quote_currency, turnover_threshold)

2023-10-21 20:44:52. 2023-10-21 03:34:44 - 2023-10-21 20:43:02.
2023-10-21 20:44:52. Timedelta: 0 days 17 hours 8 minutes 18 seconds.
2023-10-21 20:44:52. Market data saved in db.
2023-10-21 20:44:52. Stats saved in db.
2023-10-21 20:44:52. Watchlist saved in db.
2023-10-21 20:44:52. Report created in: 0:02:24.954371.

In [5]:
binance_futures = binancefut.stats

In [6]:
binance_futures.head()

     ticker           mark_price               oi_usd        open_interest      open_interest_y             turnover               trades   open_interest_perc        turnover_perc          trades_perc           price_perc                 date               date_y
0   BTCUSDT         30,109.10000  2,914,217,871.00000         96,812.00000         90,248.00000  7,502,376,775.00000      2,776,677.00000              7.27329            -53.55199            -48.12559              1.80902  2023-10-21 20:43:02  2023-10-21 03:34:44
1   ETHUSDT          1,632.10492  1,294,253,498.00000        792,781.00000        786,233.00000  2,502,310,266.00000      1,462,088.00000              0.83283            -39.32364            -37.45332              1.82328  2023-10-21 20:43:23  2023-10-21 03:35:04
2   SOLUSDT             29.28100    192,964,662.00000      6,578,265.00000      6,582,417.00000  1,807,090,679.00000      2,039,964.00000             -0.06308             -3.00782              2.90744              9.60502  2023-10-21 20:44:25  2023-10-21 03:36:03
3  LINKUSDT              8.94400    122,419,770.00000     13,675,055.00000     10,558,866.00000    893,904,518.00000      1,444,085.00000             29.51253            280.28981            236.63224             18.15249  2023-10-21 20:43:51  2023-10-21 03:35:31
4  BONDUSDT              4.04178     19,905,494.00000      4,935,654.00000      5,795,615.00000    717,616,028.00000      3,435,667.00000            -14.83813            -27.92725            -22.13911             -6.69955  2023-10-21 20:43:00  2023-10-21 03:34:42

<font size="5">OPEN_INTEREST_PERC</font>

In [7]:
fut_oi_perc = binance_futures.sort_values('open_interest_perc', ascending=False).head(10).reset_index(drop=True)
fut_oi_perc

          ticker           mark_price               oi_usd        open_interest      open_interest_y             turnover               trades   open_interest_perc        turnover_perc          trades_perc           price_perc                 date               date_y
0  1000FLOKIUSDT              0.02528     17,393,528.00000    689,672,013.00000    256,648,742.00000    339,927,668.00000      1,212,368.00000            168.72215            762.53840            532.40345             23.84243  2023-10-21 20:42:30  2023-10-21 03:34:13
1       AGLDUSDT              0.64330      7,073,412.00000     11,036,195.00000      4,305,590.00000     53,710,207.00000        424,861.00000            156.32248          1,324.78277            755.29855             18.34069  2023-10-21 20:42:37  2023-10-21 03:34:19
2        ICXUSDT              0.20560      5,009,903.00000     24,367,234.00000     15,869,116.00000     78,288,961.00000        442,885.00000             53.55130            555.69204            351.53644              7.64398  2023-10-21 20:43:39  2023-10-21 03:35:19
3        BSVUSDT             54.13000      9,075,964.00000        167,486.00000        113,402.00000    153,441,340.00000        601,514.00000             47.69228             99.34930            107.76609              2.38339  2023-10-21 20:43:01  2023-10-21 03:34:42
4       EGLDUSDT             25.83000     12,148,873.00000        469,794.00000        346,130.00000     45,811,136.00000        181,712.00000             35.72762            -34.80719            -35.31562              5.49212  2023-10-21 20:43:20  2023-10-21 03:35:01
5       LINKUSDT              8.94400    122,419,770.00000     13,675,055.00000     10,558,866.00000    893,904,518.00000      1,444,085.00000             29.51253            280.28981            236.63224             18.15249  2023-10-21 20:43:51  2023-10-21 03:35:31
6        FLMUSDT              0.07011     10,331,529.00000    147,382,320.00000    115,068,090.00000    108,736,005.00000        229,139.00000             28.08270            641.57043            482.88774              7.05909  2023-10-21 20:43:25  2023-10-21 03:35:06
7        LPTUSDT              5.76139      8,545,091.00000      1,482,900.00000      1,168,834.00000     33,066,743.00000        173,635.00000             26.87003            266.86989            155.01182              4.84848  2023-10-21 20:43:53  2023-10-21 03:35:33
8        APTUSDT              5.68000     51,388,743.00000      9,015,124.00000      7,374,347.00000    330,898,422.00000        696,435.00000             22.24979            360.56922            245.83985             12.34177  2023-10-21 20:42:43  2023-10-21 03:34:25
9       ARKMUSDT              0.32580      5,768,261.00000     17,706,716.00000     14,910,921.00000     15,887,222.00000         92,819.00000             18.74998             31.07829             22.60941              5.22370  2023-10-21 20:42:44  2023-10-21 03:34:26

<font size="5">PRICE_PERC</font>

In [8]:
fut_price_perc = binance_futures.sort_values('price_perc', ascending=False).head(10).reset_index(drop=True)
fut_price_perc

          ticker           mark_price               oi_usd        open_interest      open_interest_y             turnover               trades   open_interest_perc        turnover_perc          trades_perc           price_perc                 date               date_y
0  1000FLOKIUSDT              0.02528     17,393,528.00000    689,672,013.00000    256,648,742.00000    339,927,668.00000      1,212,368.00000            168.72215            762.53840            532.40345             23.84243  2023-10-21 20:42:30  2023-10-21 03:34:13
1       AGLDUSDT              0.64330      7,073,412.00000     11,036,195.00000      4,305,590.00000     53,710,207.00000        424,861.00000            156.32248          1,324.78277            755.29855             18.34069  2023-10-21 20:42:37  2023-10-21 03:34:19
2       LINKUSDT              8.94400    122,419,770.00000     13,675,055.00000     10,558,866.00000    893,904,518.00000      1,444,085.00000             29.51253            280.28981            236.63224             18.15249  2023-10-21 20:43:51  2023-10-21 03:35:31
3        APTUSDT              5.68000     51,388,743.00000      9,015,124.00000      7,374,347.00000    330,898,422.00000        696,435.00000             22.24979            360.56922            245.83985             12.34177  2023-10-21 20:42:43  2023-10-21 03:34:25
4        BLZUSDT              0.19782     37,494,285.00000    194,605,515.00000    222,554,226.00000    248,158,040.00000      1,174,064.00000            -12.55816             19.55939             13.61287             11.69035  2023-10-21 20:42:57  2023-10-21 03:34:39
5        FTMUSDT              0.20270     26,267,326.00000    129,420,155.00000    109,420,922.00000     92,770,218.00000        212,023.00000             18.27734             93.58195             87.66585             10.92223  2023-10-21 20:43:28  2023-10-21 03:35:09
6        SOLUSDT             29.28100    192,964,662.00000      6,578,265.00000      6,582,417.00000  1,807,090,679.00000      2,039,964.00000             -0.06308             -3.00782              2.90744              9.60502  2023-10-21 20:44:25  2023-10-21 03:36:03
7        EDUUSDT              0.42250      3,656,657.00000      8,660,843.00000      8,037,210.00000     12,428,892.00000         81,195.00000              7.75932             51.45590             37.47418              8.19462  2023-10-21 20:43:19  2023-10-21 03:35:00
8   1000PEPEUSDT              0.00071     24,624,344.00000 34,972,793,091.00000 33,800,635,116.00000    167,461,137.00000        582,967.00000              3.46786             61.46804             58.54031              7.73425  2023-10-21 20:42:32  2023-10-21 03:34:14
9        ICXUSDT              0.20560      5,009,903.00000     24,367,234.00000     15,869,116.00000     78,288,961.00000        442,885.00000             53.55130            555.69204            351.53644              7.64398  2023-10-21 20:43:39  2023-10-21 03:35:19

<font size="5">FUNDING_FEE</font>

In [9]:
fut_funding = binancefut.funding.head(10)
fut_funding

          ticker           mark_price             turnover               oi_usd        open_interest               trades             trad/min              funding                 date
0        RIFUSDT              0.11977    101,610,977.00000      3,468,495.00000     28,908,944.00000        534,660.00000          1,435.00000             -0.00277  2023-10-21 20:44:18
1  1000FLOKIUSDT              0.02528    339,927,668.00000     17,393,528.00000    689,672,013.00000      1,212,368.00000            842.00000             -0.00235  2023-10-21 20:42:30
2       ORBSUSDT              0.04313    203,382,440.00000     13,684,268.00000    317,647,817.00000      1,102,670.00000            766.00000             -0.00202  2023-10-21 20:44:09
3       STPTUSDT              0.06151      8,618,382.00000      2,822,251.00000     45,905,183.00000         57,505.00000             40.00000             -0.00125  2023-10-21 20:44:29
4      STRAXUSDT              0.66378     87,869,002.00000      8,401,036.00000     12,701,899.00000        422,832.00000            294.00000             -0.00057  2023-10-21 20:44:30
5     PENDLEUSDT              0.73929     10,325,480.00000      3,551,704.00000      4,804,145.00000         72,879.00000             51.00000             -0.00052  2023-10-21 20:44:11
6        SNXUSDT              2.09500     22,485,546.00000     11,259,586.00000      5,382,212.00000        104,420.00000             72.00000             -0.00046  2023-10-21 20:44:25
7        APTUSDT              5.68000    330,898,422.00000     51,388,743.00000      9,015,124.00000        696,435.00000            483.00000             -0.00036  2023-10-21 20:42:43
8        ENJUSDT              0.21460      9,640,134.00000     11,496,771.00000     53,523,142.00000         52,005.00000             36.00000             -0.00031  2023-10-21 20:43:21
9        ACHUSDT              0.01381      4,482,748.00000      2,828,306.00000    204,653,076.00000         31,495.00000             22.00000             -0.00025  2023-10-21 20:42:35

<font size="8">BINANCE_SPOT</font>

In [10]:
save_watchlist=True
save_in_db=True
main_quote_currency='USDT'
secondary_quote_currency='BUSD'
turnover_threshold = '10 000 000'

In [11]:
binancespot = exchanges_stats.BinanceSpotStats(save_watchlist, save_in_db, main_quote_currency, secondary_quote_currency, turnover_threshold)

2023-10-21 20:44:54. Symbols filtered: USDT, BUSD, TRADING.
2023-10-21 20:44:56. BinanceSpotStats: 2023-10-21 03:36:32 - 2023-10-21 20:44:55.
2023-10-21 20:44:56. Timedelta: 0 days 17 hours 8 minutes 23 seconds.
2023-10-21 20:44:56. Market data saved in db.
2023-10-21 20:44:56. Stats saved in db.
       exchange     ticker                price             turnover  plotted                 date
0  BINANCE_SPOT   LINKUSDT              8.94400    119,852,316.58920    False  2023-10-21 20:44:55
1  BINANCE_SPOT  FLOKIUSDT              0.00003     41,402,218.11693    False  2023-10-21 20:44:55
2  BINANCE_SPOT    BLZUSDT              0.19900     30,355,648.64420    False  2023-10-21 20:44:55
3  BINANCE_SPOT    RIFUSDT              0.12020     29,502,554.11330    False  2023-10-21 20:44:55
4  BINANCE_SPOT  LEVERUSDT              0.00127     17,997,490.03893    False  2023-10-21 20:44:55
5  BINANCE_SPOT  STEEMUSDT              0.22230     12,376,147.79108    False  2023-10-21 20:44:55
6  BINANCE_SPOT    FLMUSDT              0.07010     11,624,591.26070    False  2023-10-21 20:44:55
7  BINANCE_SPOT     MCUSDT              0.44030     11,128,657.15729    False  2023-10-21 20:44:55
2023-10-21 20:44:56. Watchlist disabled in spot.
2023-10-21 20:44:56. Report created in: 0:00:03.889100.

In [12]:
binance_spot = binancespot.to_report

In [13]:
binance_spot.head(10)

      ticker                price             turnover           turnover_y               trades        turnover_perc          trades_perc           price_perc                 date               date_y
0    BTCUSDT         30,118.23000    817,015,805.81360  1,750,104,197.56096      1,066,724.00000            -53.31616            -43.93757              1.84857  2023-10-21 20:44:55  2023-10-21 03:36:32
1    ETHUSDT          1,631.67000    277,295,846.20353    503,510,819.12959        450,183.00000            -44.92753            -30.76941              1.78789  2023-10-21 20:44:55  2023-10-21 03:36:32
2    SOLUSDT             29.29000    246,409,011.30530    198,274,684.61170        302,786.00000             24.27659              7.24884              9.61826  2023-10-21 20:44:55  2023-10-21 03:36:32
3   USDCUSDT              0.99960    144,832,352.96260    500,094,339.17650         70,132.00000            -71.03899            -43.94642              0.01001  2023-10-21 20:44:55  2023-10-21 03:36:32
4   LINKUSDT              8.94400    119,852,316.58920     32,610,050.55952        342,703.00000            267.53183            267.04152             18.15059  2023-10-21 20:44:55  2023-10-21 03:36:32
5    XRPUSDT              0.52370    102,182,494.85070    190,420,374.52580        134,932.00000            -46.33847            -43.89079              1.84753  2023-10-21 20:44:55  2023-10-21 03:36:32
6  FDUSDUSDT              0.99960    100,929,250.57170    231,811,070.01400         69,415.00000            -56.46056            -34.34071             -0.01000  2023-10-21 20:44:55  2023-10-21 03:36:32
7   LOOMUSDT              0.11080     67,636,223.13165    132,666,692.88237        333,036.00000            -49.01793            -43.92087            -11.55811  2023-10-21 20:44:55  2023-10-21 03:36:32
8   TUSDUSDT              0.99900     50,261,512.37780     72,282,853.86190         26,057.00000            -30.46551            -36.80394              0.00000  2023-10-21 20:44:55  2023-10-21 03:36:32
9    BNBUSDT            214.80000     46,693,409.65360     73,995,387.07320        105,979.00000            -36.89686            -24.09632              1.32075  2023-10-21 20:44:55  2023-10-21 03:36:32

<font size="5">PRICE_PERC</font>

In [14]:
spot_price_perc = binance_spot.sort_values('price_perc', ascending=False).head(10).reset_index(drop=True)
spot_price_perc

      ticker                price             turnover           turnover_y               trades        turnover_perc          trades_perc           price_perc                 date               date_y
0    RIFUSDT              0.12020     29,502,554.11330     25,957,880.11330        208,621.00000             13.65548             19.39963             26.26050  2023-10-21 20:44:55  2023-10-21 03:36:32
1  FLOKIUSDT              0.00003     41,402,218.11693      8,046,784.63445        197,215.00000            414.51878            437.73688             23.94297  2023-10-21 20:44:55  2023-10-21 03:36:32
2   LINKUSDT              8.94400    119,852,316.58920     32,610,050.55952        342,703.00000            267.53183            267.04152             18.15059  2023-10-21 20:44:55  2023-10-21 03:36:32
3     MCUSDT              0.44030     11,128,657.15729      2,722,741.41621         71,552.00000            308.72986            170.72266             17.53871  2023-10-21 20:44:55  2023-10-21 03:36:32
4    BLZUSDT              0.19900     30,355,648.64420     19,343,233.10970        124,057.00000             56.93162             50.18825             12.49293  2023-10-21 20:44:55  2023-10-21 03:36:32
5    APTUSDT              5.68780     44,104,156.36458     11,337,283.11845        175,832.00000            289.01874            300.61060             12.33607  2023-10-21 20:44:55  2023-10-21 03:36:32
6    FTMUSDT              0.20250     13,070,368.34430      5,499,340.26730         51,172.00000            137.67157            119.46219             10.77681  2023-10-21 20:44:55  2023-10-21 03:36:32
7    SOLUSDT             29.29000    246,409,011.30530    198,274,684.61170        302,786.00000             24.27659              7.24884              9.61826  2023-10-21 20:44:55  2023-10-21 03:36:32
8  STEEMUSDT              0.22230     12,376,147.79108      2,805,891.08602         72,852.00000            341.07727            286.74948              8.12257  2023-10-21 20:44:55  2023-10-21 03:36:32
9   PEPEUSDT              0.00000     13,426,229.20292      7,976,527.41924         21,071.00000             68.32173             91.17220              7.57576  2023-10-21 20:44:55  2023-10-21 03:36:32

<font size="5">TURNOVER_PERC</font>

In [15]:
spot_turnover_perc = binance_spot.sort_values('turnover_perc', ascending=False).head(10).reset_index(drop=True)
spot_turnover_perc

      ticker                price             turnover           turnover_y               trades        turnover_perc          trades_perc           price_perc                 date               date_y
0    FLMUSDT              0.07010     11,624,591.26070      1,391,232.25670         54,673.00000            735.56079            614.77317              7.02290  2023-10-21 20:44:55  2023-10-21 03:36:32
1  FLOKIUSDT              0.00003     41,402,218.11693      8,046,784.63445        197,215.00000            414.51878            437.73688             23.94297  2023-10-21 20:44:55  2023-10-21 03:36:32
2  STEEMUSDT              0.22230     12,376,147.79108      2,805,891.08602         72,852.00000            341.07727            286.74948              8.12257  2023-10-21 20:44:55  2023-10-21 03:36:32
3     MCUSDT              0.44030     11,128,657.15729      2,722,741.41621         71,552.00000            308.72986            170.72266             17.53871  2023-10-21 20:44:55  2023-10-21 03:36:32
4  LEVERUSDT              0.00127     17,997,490.03893      4,471,156.63541         53,247.00000            302.52426            226.22840              2.00642  2023-10-21 20:44:55  2023-10-21 03:36:32
5    APTUSDT              5.68780     44,104,156.36458     11,337,283.11845        175,832.00000            289.01874            300.61060             12.33607  2023-10-21 20:44:55  2023-10-21 03:36:32
6   LINKUSDT              8.94400    119,852,316.58920     32,610,050.55952        342,703.00000            267.53183            267.04152             18.15059  2023-10-21 20:44:55  2023-10-21 03:36:32
7    FTMUSDT              0.20250     13,070,368.34430      5,499,340.26730         51,172.00000            137.67157            119.46219             10.77681  2023-10-21 20:44:55  2023-10-21 03:36:32
8   PEPEUSDT              0.00000     13,426,229.20292      7,976,527.41924         21,071.00000             68.32173             91.17220              7.57576  2023-10-21 20:44:55  2023-10-21 03:36:32
9    BLZUSDT              0.19900     30,355,648.64420     19,343,233.10970        124,057.00000             56.93162             50.18825             12.49293  2023-10-21 20:44:55  2023-10-21 03:36:32

<font size="8">KUCOIN_SPOT</font>

In [16]:
kucoin_spot = exchanges_stats.KucoinSpotStats(save_in_db=True, main_quote_currency='USDT', secondary_quote_currency='USDC').stats

2023-10-21 20:44:58. Kucoin: USDT and USDC pairs included.
2023-10-21 20:44:58. KucoinSpotStats: 2023-10-21 03:36:35 - 2023-10-21 20:44:58.
2023-10-21 20:44:58. Timedelta: 0 days 17 hours 8 minutes 23 seconds.
2023-10-21 20:44:58. KucoinSpotStats: current market data saved in db.
2023-10-21 20:44:58. KucoinSpotStats: stats saved in db.
2023-10-21 20:44:58. Report created in: 0:00:01.331312.

In [17]:
kucoin_spot.head()

     ticker                price              price_y             turnover           turnover_y           price_perc        turnover_perc                 date               date_y
0   BTCUSDT         30,116.70000         29,572.90000     81,170,879.98414    138,771,030.23077              1.83885            -41.50733  2023-10-21 20:44:58  2023-10-21 03:36:35
1   SOLUSDT             29.28400             26.71700     21,296,215.15009     21,092,169.20266              9.60811              0.96740  2023-10-21 20:44:58  2023-10-21 03:36:35
2   XRPUSDT              0.52378              0.51423     13,394,943.72747     19,800,304.55854              1.85715            -32.34981  2023-10-21 20:44:58  2023-10-21 03:36:35
3   ETHUSDT          1,631.87000          1,602.95000     12,500,359.09440     21,525,411.75625              1.80417            -41.92743  2023-10-21 20:44:58  2023-10-21 03:36:35
4  LINKUSDT              8.94460              7.56930      8,936,243.95082      2,310,032.01690             18.16945            286.84503  2023-10-21 20:44:58  2023-10-21 03:36:35

<font size="5">PRICE_PERC</font>

In [18]:
oi_perc_tails = kucoin_spot.sort_values('price_perc', ascending=False).head(10).reset_index(drop=True)
oi_perc_tails

       ticker                price              price_y             turnover           turnover_y           price_perc        turnover_perc                 date               date_y
0    DOSEUSDC              0.00540              0.00223         21,088.24991          1,702.19480            141.93548          1,138.88581  2023-10-21 20:44:58  2023-10-21 03:36:35
1   FLOKIUSDT              0.00003              0.00002      3,345,071.75779        931,921.11550             23.99351            258.94366  2023-10-21 20:44:58  2023-10-21 03:36:35
2     RFDUSDT              0.00000              0.00000         77,212.65069          7,328.77954             22.92273            953.55401  2023-10-21 20:44:58  2023-10-21 03:36:35
3  PEPEUPUSDT              0.01976              0.01622         43,240.79836         38,999.51144             21.85361             10.87523  2023-10-21 20:44:58  2023-10-21 03:36:35
4  LINAUPUSDT              0.76850              0.63230          3,319.33147          3,655.64761             21.54041             -9.19991  2023-10-21 20:44:58  2023-10-21 03:36:35
5    LITHUSDT              0.00027              0.00023         50,486.56448          2,751.04209             19.98232          1,735.17965  2023-10-21 20:44:58  2023-10-21 03:36:35
6    AGLDUSDT              0.64270              0.54350         99,075.23371         11,937.11923             18.25207            729.97608  2023-10-21 20:44:58  2023-10-21 03:36:35
7    LINKUSDT              8.94460              7.56930      8,936,243.95082      2,310,032.01690             18.16945            286.84503  2023-10-21 20:44:58  2023-10-21 03:36:35
8     VXVUSDT              0.20040              0.17030         39,984.03728         35,054.85092             17.67469             14.06135  2023-10-21 20:44:58  2023-10-21 03:36:35
9   AIPADUSDT              0.10562              0.09000        119,670.83373         90,559.86242             17.35556             32.14556  2023-10-21 20:44:58  2023-10-21 03:36:35

<font size="5">TURNOVER_PERC</font>

In [19]:
turnover_perc_tails = kucoin_spot.sort_values('turnover_perc', ascending=False).head(10).reset_index(drop=True)
turnover_perc_tails

          ticker                price              price_y             turnover           turnover_y           price_perc        turnover_perc                 date               date_y
0   COMPDOWNUSDT              3.67170              3.76870          1,529.18319             11.59605             -2.57383         13,087.10035  2023-10-21 20:44:58  2023-10-21 03:36:35
1  STORJDOWNUSDT             10.61070             10.71433            633.83191             10.99999             -0.96719          5,662.11387  2023-10-21 20:44:58  2023-10-21 03:36:35
2     COMPUPUSDT              3.05370              2.70090          1,121.86075             53.74987             13.06231          1,987.18773  2023-10-21 20:44:58  2023-10-21 03:36:35
3       LITHUSDT              0.00027              0.00023         50,486.56448          2,751.04209             19.98232          1,735.17965  2023-10-21 20:44:58  2023-10-21 03:36:35
4        XNLUSDT              0.00681              0.00647         22,666.91899          1,290.47831              5.25502          1,656.47423  2023-10-21 20:44:58  2023-10-21 03:36:35
5        ATAUSDT              0.07661              0.07305          9,449.48224            680.89470              4.87337          1,287.80375  2023-10-21 20:44:58  2023-10-21 03:36:35
6       DOSEUSDC              0.00540              0.00223         21,088.24991          1,702.19480            141.93548          1,138.88581  2023-10-21 20:44:58  2023-10-21 03:36:35
7        ORCUSDT              0.05091              0.05089         27,991.02542          2,469.48203              0.03930          1,033.47759  2023-10-21 20:44:58  2023-10-21 03:36:35
8        RFDUSDT              0.00000              0.00000         77,212.65069          7,328.77954             22.92273            953.55401  2023-10-21 20:44:58  2023-10-21 03:36:35
9   PERPDOWNUSDT             10.49851             11.08489            117.60890             11.43422             -5.28990            928.56962  2023-10-21 20:44:58  2023-10-21 03:36:35

<font size="8">WATCHLIST</font>

In [20]:
executions.symbols_in_play()

          exchange         ticker                price             turnover  plotted                date
0  BINANCE_FUTURES       LINKUSDT              8.94400    893,904,518.00000    False 2023-10-21 20:43:51
1  BINANCE_FUTURES  1000FLOKIUSDT              0.02528    339,927,668.00000    False 2023-10-21 20:42:30
2  BINANCE_FUTURES        APTUSDT              5.68000    330,898,422.00000    False 2023-10-21 20:42:43
3  BINANCE_FUTURES        BLZUSDT              0.19782    248,158,040.00000    False 2023-10-21 20:42:57
4  BINANCE_FUTURES        BSVUSDT             54.13000    153,441,340.00000    False 2023-10-21 20:43:01
5  BINANCE_FUTURES        ICXUSDT              0.20560     78,288,961.00000    False 2023-10-21 20:43:39
6  BINANCE_FUTURES       AGLDUSDT              0.64330     53,710,207.00000    False 2023-10-21 20:42:37
7  BINANCE_FUTURES       EGLDUSDT             25.83000     45,811,136.00000    False 2023-10-21 20:43:20